import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('./stageStatus.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { instructionBlocks, stageStatus } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
assert.equal(instructionBlocks('scheduled'), false);
assert.equal(instructionBlocks('applied'), false);
assert.equal(instructionBlocks('delivered'), true);
assert.equal(instructionBlocks('needs_input'), true);
assert.equal(stageStatus('running', false), 'running');
assert.equal(stageStatus('repairing', false), 'repairing');
assert.equal(stageStatus('running', false, '', false, 'repair'), 'repairing');
assert.equal(stageStatus('running', true), 'paused');
assert.equal(stageStatus('running', true, '', true), 'needs_input');
assert.equal(stageStatus('waiting_external', true, 'RUNNING'), 'running');
assert.equal(stageStatus('waiting_external', true, 'PENDING'), 'queued');
assert.equal(stageStatus('succeeded', true), 'succeeded');
assert.equal(stageStatus('cancelled', true), 'cancelled');
assert.equal(stageStatus('awaiting_input', false), 'needs_input');
console.log('stage status regression checks passed');
