"""phase15_transcript_events

Revision ID: 8a1a7091f54f
Revises: ca1a34d0a1b6
Create Date: 2026-05-25 23:38:36.712747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8a1a7091f54f'
down_revision: Union[str, None] = 'ca1a34d0a1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('heartbeat_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['heartbeat_id'], ['heartbeat_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_events_heartbeat_id'), 'transcript_events', ['heartbeat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_events_heartbeat_id'), table_name='transcript_events')
    op.drop_table('transcript_events')
    # ### end Alembic commands ###
