"""phase14_objectives_table

Revision ID: ca1a34d0a1b6
Revises: f2389101ff08
Create Date: 2026-05-25 21:51:43.302038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ca1a34d0a1b6'
down_revision: Union[str, None] = 'f2389101ff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schedule_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('iteration_budget', sa.Integer(), server_default='3', nullable=False),
    sa.Column('target_accuracy', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.String(length=36), nullable=False),
    sa.Column('best_accuracy_ever', sa.Float(), server_default='-1.0', nullable=False),
    sa.Column('best_registry_tag', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objectives')
    # ### end Alembic commands ###
