"""phase9_supervisor_ticket_id

Revision ID: e874e86c9cf5
Revises: c817521a7b52
Create Date: 2026-05-23 07:45:21.347248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e874e86c9cf5'
down_revision: Union[str, None] = 'c817521a7b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('supervisor_ticket_id', sa.String(length=64), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'supervisor_ticket_id')
    # ### end Alembic commands ###
