"""phase13_iteration_tracking

Revision ID: f2389101ff08
Revises: e874e86c9cf5
Create Date: 2026-05-25 21:44:36.702763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2389101ff08'
down_revision: Union[str, None] = 'e874e86c9cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('iteration_budget', sa.Integer(), server_default='5', nullable=False))
    op.add_column('runs', sa.Column('iterations_completed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('runs', sa.Column('target_accuracy', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('runs', sa.Column('best_accuracy', sa.Float(), server_default='-1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'best_accuracy')
    op.drop_column('runs', 'target_accuracy')
    op.drop_column('runs', 'iterations_completed')
    op.drop_column('runs', 'iteration_budget')
    # ### end Alembic commands ###
