"""phase16_heartbeat_cost

Revision ID: fbf81d644eca
Revises: 8a1a7091f54f
Create Date: 2026-05-26 01:30:47.504339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fbf81d644eca'
down_revision: Union[str, None] = '8a1a7091f54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeat_runs', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('heartbeat_runs', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('heartbeat_runs', sa.Column('cached_input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('heartbeat_runs', sa.Column('reasoning_output_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('heartbeat_runs', sa.Column('estimated_cost_usd', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heartbeat_runs', 'estimated_cost_usd')
    op.drop_column('heartbeat_runs', 'reasoning_output_tokens')
    op.drop_column('heartbeat_runs', 'cached_input_tokens')
    op.drop_column('heartbeat_runs', 'output_tokens')
    op.drop_column('heartbeat_runs', 'input_tokens')
    # ### end Alembic commands ###
